### ISSUE TITLE
Yum not working

### ISSUE THREAD

**Issue by recursify** [ryansb/sklearn-build-lambda#7]
Apologies in advance, I'm new to Docker.

I suspect this has nothing to do with your script, but I'm not able to run `yum` with the latest `amazonlinux` image.  The same command works just fine if I run on the latest version of `centos`.

```
$ docker run -it amazonlinux yum
There was a problem importing one of the Python modules
required to run yum. The error leading to this problem was:

   No module named yum

Please install a package which provides this module, or
verify that the module is installed correctly.

It's possible that the above module doesn't match the
current version of Python, which is:
2.7.12 (default, Sep  1 2016, 22:14:00)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

If you cannot solve this problem yourself, please go to
the yum faq at:
  http://yum.baseurl.org/wiki/Faq
```

In fact, the `python` version seems pretty crippled as well:

```
$ docker run -it amazonlinux python -c 'import os.path'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named path
```

I'm running docker version 17.03.1-ce-mac5, and amazonlinux with image ID 8ae6f52035b5

**Comment by recursify** [comment]
Okay - got it working, please close this issue.

I think it may be because I was using the native Docker for Mac, instead of Docker Toolbox.  I uninstalled Docker for Mac, upgraded Docker Toolbox, and it works like a charm.

**Comment by ryansb** [comment]
That's very strange, but looks like the issue was specific to your host as I can't reproduce.
